<a href="https://colab.research.google.com/github/RiyaMaurya1/BridgeAbility/blob/main/ANN_Back_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
X = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

X.shape

(3, 4)

In [24]:
inputneurons = X.shape[1]

# equal to no. of features
hiddenneurons = 4 

outputneurons = 1



In [25]:
weightshidden = np.random.uniform(size = (inputneurons, hiddenneurons))
biashidden = np.random.uniform(size = (1, hiddenneurons))
biasoutput = np.random.uniform(size = (1, outputneurons))
weightsoutput = np.random.uniform(size = (hiddenneurons, outputneurons))

In [26]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))


In [27]:
# feed forward 

# Step 1: Apply linear equation
fx1 = np.dot(X, weightshidden) + biashidden

fx1

array([[0.88211792, 1.46183689, 1.61588339, 1.6880048 ],
       [1.70920422, 2.05403576, 2.20516305, 2.53793484],
       [1.75335449, 2.01808979, 1.17256779, 2.21507785]])

In [28]:
# Step 2: Apply activation for non-linearity
z = sigmoid(fx1)

z

array([[0.70726091, 0.81181346, 0.83422662, 0.84396159],
       [0.84673304, 0.88635478, 0.9007122 , 0.92675877],
       [0.8523754 , 0.88268335, 0.76360884, 0.90159536]])

In [29]:
# Step - 3 : apply linear equation on output of hidden layer
fx2 = np.dot(z, weightsoutput) + biasoutput

# Step - 4 : apply activation on output layer
output = sigmoid(fx2)

In [30]:
output

array([[0.90690443],
       [0.92083728],
       [0.91734596]])

In [31]:
y

array([[1],
       [1],
       [0]])

In [32]:
# As there is huge difference between output and target, we will perform backpropagation to rewrite the weights and get closer results. 

In [33]:
# Performing Backpropogation

In [34]:
# Calculate loss on output layer
outputloss = y - output

outputloss

array([[ 0.09309557],
       [ 0.07916272],
       [-0.91734596]])

In [35]:
def derivativeofsigmoid(x):
  return x*(1-x)

In [36]:
outputslope = derivativeofsigmoid(output)

In [37]:
output

array([[0.90690443],
       [0.92083728],
       [0.91734596]])

In [38]:
outputslope

array([[0.08442879],
       [0.07289598],
       [0.07582235]])

In [40]:
deltaoutput = outputloss * outputslope
deltaoutput

array([[ 0.00785995],
       [ 0.00577064],
       [-0.06955532]])

In [41]:
# deltaout shape = 3,1
# weightoutput shape = 4, 1
# so we need to transpose weightsoutput 
hiddenloss = np.dot(deltaoutput, weightsoutput.T)

hiddenloss

array([[ 0.00605681,  0.00212457,  0.00236643,  0.00282185],
       [ 0.00444681,  0.00155982,  0.0017374 ,  0.00207175],
       [-0.05359876, -0.01880102, -0.02094136, -0.02497148]])

In [44]:
hiddenslope = derivativeofsigmoid(hiddenloss)

In [45]:
hiddenslope

array([[ 0.00602012,  0.00212005,  0.00236083,  0.00281388],
       [ 0.00442704,  0.00155739,  0.00173438,  0.00206746],
       [-0.05647159, -0.01915449, -0.0213799 , -0.02559505]])

In [49]:
hiddendelta = hiddenloss*hiddenslope

In [47]:
hiddendelta

array([[3.64627501e-05, 4.50419692e-06, 5.58675132e-06, 7.94034858e-06],
       [1.96861916e-05, 2.42925145e-06, 3.01330069e-06, 4.28327059e-06],
       [3.02680685e-03, 3.60123953e-04, 4.47724320e-04, 6.39146172e-04]])

In [66]:
# weights and bias optimisation

# learning rate = alpha
alpha = 0.3

In [67]:
# z is our hidden layer 
weightsoutput = weightsoutput - z.T.dot(deltaoutput) * alpha
weightshidden = weightshidden - X.T.dot(hiddendelta) * alpha
biasoutput = biasoutput - np.sum(deltaoutput) * alpha
biashidden = biashidden - np.sum(hiddendelta) * alpha

In [ ]:
# Now putting everything in a loop 
# Run from down here

In [68]:
epochs = 3000

weightshidden = np.random.uniform(size=(inputneurons, hiddenneurons))
biashidden = np.random.uniform(size=(1,hiddenneurons))
weightsoutput = np.random.uniform(size=(hiddenneurons, outputneurons))
biasoutput = np.random.uniform(size=(1,outputneurons))

for i in range(epochs):

  # Feedforward
  # Step - 1 - apply linear equation
  fx1 = np.dot(X, weightshidden) + biashidden
  # Step - 2 - apply activation for non-linearity
  z = sigmoid(fx1)
  # Step - 3 : apply linear equation on output of hidden layer
  fx2 = np.dot(z, weightsoutput) + biasoutput
  # Step - 4 : apply activation on output layer
  output = sigmoid(fx2)

  # Backpropagation
  outputloss = output - y
  outputslope = derivativeofsigmoid(output)
  deltaoutput = outputloss * outputslope
  
  hiddenloss = np.dot(deltaoutput, weightsoutput.T)
  hiddenslope = derivativeofsigmoid(z)
  hiddendelta = hiddenloss * hiddenslope

  # Weights and Bias Optimization
  weightsoutput = weightsoutput - z.T.dot(deltaoutput) * alpha
  weightshidden = weightshidden - X.T.dot(hiddendelta) * alpha
  biasoutput = biasoutput - np.sum(deltaoutput) * alpha
  biashidden = biashidden - np.sum(hiddendelta) * alpha

In [69]:
output

array([[0.98921212],
       [0.98095774],
       [0.02549425]])

In [70]:
outputloss

array([[-0.01078788],
       [-0.01904226],
       [ 0.02549425]])